default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planshopcook_development

test:
  <<: *default
  database: planshopcook_test

production:
  <<: *default
  database: planshopcook
  username: planshopcook
  password: If54EdSwMFd1reORA8of
  host: planshopcook.cudmaju8glih.us-east-2.rds.amazonaws.com
  port: 5432